spring.application.name=backend

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/workflowAutomation
spring.datasource.username=postgres
spring.datasource.password=postgres

#hibernate 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate